### ISSUE TITLE
Using the compel library to processing promp

### ISSUE THREAD

**Issue by ytzfhqs** [natsunoyuki/diffuser_tools#1]
Hi! I came across your blog on medium, thanks for doing the tutorial, it helped me a lot.

I noticed that in order to get around the 77 tokens limit of the CLIP model, you used the `get_prompt_embeddings` [function](https://github.com/huggingface/diffusers/issues/2136), but I still triggered warnings when the prompt was very long, and after checking the Huggingface diffusers [documentation](https://huggingface.co/docs/diffusers/using-diffusers/weighted_prompts#stable-diffusion-xl), I found out that I can use the [Compel library](https://github.com/damian0815/compel) to deal with this issue. No matter how long my prompt is, I don't get any more warnings, example below:

```python
class ct_pipe():
    def __init__(self, diff_model, clip_skip, torch_dtype, device):
        self.device = device
        self.pipe = DiffusionPipeline.from_pretrained(diff_model, safety_checker = None, torch_dtype = torch_dtype)
        clip_layers = self.pipe.text_encoder.text_model.encoder.layers
        self.pipe.text_encoder.text_model.encoder.layers = clip_layers[:-clip_skip]
        self.pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(self.pipe.scheduler.config)
        self.pipe = self.pipe.to(device)
        clear_output()

    def promp_embeds(self):
        compel = Compel(tokenizer=self.pipe.tokenizer, text_encoder=self.pipe.text_encoder)
        self.con_embeds = compel([self.prompt])
        self.neg_embeds = compel([self.negative_prompt])
        return self
    
    def generat_image(self):
        self.image = self.pipe(prompt_embeds = self.con_embeds,
                               negative_prompt_embeds = self.neg_embeds,
                               width = self.width,
                               height = self.height,
                               guidance_scale = self.cfg,
                               num_inference_steps = self.steps,
                               num_images_per_prompt = 2
                              ).images
        return self
        
    def show_image(self, prompt, negative_prompt, width, height, cfg, steps):
        self.prompt = prompt
        self.negative_prompt = negative_prompt
        self.width = width
        self.height = height
        self.cfg = cfg
        self.steps = steps
        self.promp_embeds()
        self.generat_image()
        clear_output()
        display(make_image_grid(self.image, 1, 2))
```
Please note the `promp_embeds` function, if you feel the need to update some of the code and blog related content, looking forward to your reply!

**Comment by natsunoyuki** [comment]
Hello @ytzfhqs, 

I apologize for the late reply as I have been extremely busy with work over the past few months.
Thank you for reading and for your comment!

Actually I have been wanting to work on this for some time.
In addition to the triggered warnings, the code also crashes in some cases when the negative prompt is too long.
I need to focus on other tasks and work right now - however I will surely take a look at using Compel instead in the future.
For the time being I will leave this issue as a reminder to myself

Thank you again for your interest and your suggestion!

Best regards,
Natsunoyuki

**Comment by natsunoyuki** [comment]
Update: I've updated the repository to use Compel for prompt embeddings!
The warning regarding embeddings > 77 tokens has disappeared!
Thank you again for your suggestion!

**Comment by natsunoyuki** [comment]
Update: I've updated the repository to use Compel for prompt embeddings!
The warning regarding embeddings > 77 tokens has disappeared!
Thank you again for your suggestion!

**Comment by ArjunDosajh** [comment]
How does compel handle prompts longer than the maximum token limit? Does it break the prompt into chunks of 75 and concatenate their embeddings which are separately computed?

**Comment by natsunoyuki** [comment]
Hello @ArjunDosajh, thank you for reaching out.

According to the official documentation:
https://github.com/damian0815/compel?tab=readme-ov-file#0110---add-support-for-prompts-longer-than-the-models-max-token-length
prompts longer than max_token_length will be chunked and padded out to an integer multiple of max_token_length.

I have not had the chance to read through Compel's source code in detail yet, however if you are interested I think this is where the chunking and padding happens:
https://github.com/damian0815/compel/blob/main/src/compel/embeddings_provider.py#L144

**Comment by ArjunDosajh** [comment]
As of now prompts longer than 75 tokens are handled like this: a prompt with 120 tokens would be separated into two chunks: first with 75 tokens, second with 45. Both would be padded to 75 tokens and extended with start/end tokens to 77.

This is not the best solution because it is crucial that these chunks maintain their meaning and context, so the text does not lose coherence between chunks.

Is there a way where I can split into chunks myself (let's say using an LLM to paraphrase the prompt into chunks of 75 and maintaining the meaning and context and not losing coherence)?
